<a href="https://colab.research.google.com/github/jpengtelecom/Lista_Markov/blob/main/Exercicio01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
!pip install numpy
!pip install matplotlib
!pip install scipy
!pip install numpy.linalg

  Using cached numpy-linalg-0.1.tar.gz (3.2 kB)
  Preparing metadata (setup.py) ... done
  Using cached numpy-1.18.1.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [22]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import matrix_power

matriz_transicao = [
    [0, 1/2, 1/2, 0, 0, 0],
    [1/2, 0, 0, 1/2, 0, 0],
    [1/3, 0, 0, 1/3, 1/3, 0],
    [0, 1/3, 1/3, 0, 1/3, 0],
    [0, 0, 1/2, 0, 0, 1/2],
    [0, 0, 0, 0, 0, 1]
]


matriz_transicao_1_passo = np.array(matriz_transicao)

print("A matriz de transição de 1 passo:", np.array(matriz_transicao_1_passo))

probabilidade_morte = np.linalg.matrix_power(matriz_transicao_1_passo, 3)
print("Elevando a matriz de transição de 1 passo à terceira potência :", np.array(probabilidade_morte))
probabilidade_morte = probabilidade_morte[0][5]

print("Probabilidade do rato morrer após 3 horas:", probabilidade_morte)




A matriz de transição de 1 passo: [[0.         0.5        0.5        0.         0.         0.        ]
 [0.5        0.         0.         0.5        0.         0.        ]
 [0.33333333 0.         0.         0.33333333 0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.         0.33333333 0.        ]
 [0.         0.         0.5        0.         0.         0.5       ]
 [0.         0.         0.         0.         0.         1.        ]]
Elevando a matriz de transição de 1 passo à terceira potência : [[0.         0.34722222 0.43055556 0.         0.13888889 0.08333333]
 [0.34722222 0.         0.08333333 0.34722222 0.13888889 0.08333333]
 [0.28703704 0.         0.05555556 0.28703704 0.14814815 0.22222222]
 [0.05555556 0.23148148 0.28703704 0.05555556 0.14814815 0.22222222]
 [0.         0.13888889 0.22222222 0.         0.05555556 0.58333333]
 [0.         0.         0.         0.         0.         1.        ]]
Probabilidade do rato morrer após 3 horas: 0.08333333333333333
